version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo:/data/db
    command: [--auth]
    restart: unless-stopped

networks:
  default:
    name: mongo_network